### ISSUE TITLE
[Criacao] de templates

### ISSUE THREAD

**Issue by saragilberto** [ICEI-PUC-Minas-PMV-ADS/Aplicacao-WEB---Curriculo-Online#5]
* Criação de 3 templates para disponibilizar no site;
* É de extrema importância um layout simples, contendo:
- Espaço para foto;
- Espaço para "Habilidades";
- Espaço para "Dados pessoais";
- Espaço para "Formação";
- Espaço para "Contato"

**Comment by IsraelsilvaD** [comment]
![Image](https://user-images.githubusercontent.com/130614485/235543507-5e3a2762-3f5d-4680-8c7a-9465fb164072.png)



![Image](https://user-images.githubusercontent.com/130614485/235543520-ad716454-6264-4565-8a70-42fc8e29253e.png)



![Image](https://user-images.githubusercontent.com/130614485/235543694-34ab3f29-e220-4140-a309-7d1985a16d93.png)
